version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: yarn install
      - run: npm test -- --coverage
      - codecov/upload:
          file: coverage/clover.xml
